env:
  es6: true
  node: true
extends:
  - "plugin:@typescript-eslint/eslint-recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2022
  sourceType: module
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - "node_modules/*"
overrides:
  - files: ["*.ts"]
    rules:
      no-restricted-imports: 
        - error
        - patterns: ["@aws-sdk/client-*/*"]
